Test email 2 recipients

diff --git a/.github/workflows/deliv_hmreader_openradioss_ci.yaml b/.github/workflows/deliv_hmreader_openradioss_ci.yaml
--- a/.github/workflows/deliv_hmreader_openradioss_ci.yaml
+++ b/.github/workflows/deliv_hmreader_openradioss_ci.yaml
@@ -67,218 +67,222 @@ jobs:
         run: |
           mkdir -p ${{ env.WORKDIR }}
 
-      - name: Checking delivery commit
-        working-directory: ${{ env.WORKDIR }}
-        run: |
-          # Get branch
-          export BRANCH_NAME="${GITHUB_REF#refs/heads/}"
+      # - name: Checking delivery commit
+      #   working-directory: ${{ env.WORKDIR }}
+      #   run: |
+      #     # Get branch
+      #     export BRANCH_NAME="${GITHUB_REF#refs/heads/}"
 
-          echo "BRANCH_NAME=${BRANCH_NAME}" >> $GITHUB_ENV
+      #     echo "BRANCH_NAME=${BRANCH_NAME}" >> $GITHUB_ENV
 
-          # DEV ONLY #
-          export BRANCH_NAME="dev/ci/hm_reader_intermediate"
+      #     # DEV ONLY #
+      #     export BRANCH_NAME="dev/ci/hm_reader_intermediate"
 
-          export HM_REMOTE_DIR="${HW_SOLVER_PREFIX}/${HMREADER_PREFIX}/${BRANCH_NAME}/${DELIV_COMMIT}"
-          echo "HM_REMOTE_DIR=${HM_REMOTE_DIR}" >> $GITHUB_ENV
-          # Check if the commit exist on jfrog
-          result_hm=$(jf rt s ${JF_OPTIONS} "${HM_REMOTE_DIR}/*")
+      #     export HM_REMOTE_DIR="${HW_SOLVER_PREFIX}/${HMREADER_PREFIX}/${BRANCH_NAME}/${DELIV_COMMIT}"
+      #     echo "HM_REMOTE_DIR=${HM_REMOTE_DIR}" >> $GITHUB_ENV
+      #     # Check if the commit exist on jfrog
+      #     result_hm=$(jf rt s ${JF_OPTIONS} "${HM_REMOTE_DIR}/*")
 
-          if [[ "${result_hm}" == "[]" ]]
-          then
-            echo "Commit ${DELIV_COMMIT} does not exist on Jfrog."
-            exit 1
-          fi
+      #     if [[ "${result_hm}" == "[]" ]]
+      #     then
+      #       echo "Commit ${DELIV_COMMIT} does not exist on Jfrog."
+      #       exit 1
+      #     fi
 
-          # Set correct end of step status (if not an email will be sent)
-          echo "STATUS_STEP_CHECK_DELIV_COMMIT=1" >> $GITHUB_ENV          
+      #     # Set correct end of step status (if not an email will be sent)
+      #     echo "STATUS_STEP_CHECK_DELIV_COMMIT=1" >> $GITHUB_ENV          
 
-      - name: Check all libs are present
-        run: |     
-          echo "-------------------------"
-          echo "Verify libraries on jfrog"
-          echo "-------------------------"
+      # - name: Check all libs are present
+      #   run: |     
+      #     echo "-------------------------"
+      #     echo "Verify libraries on jfrog"
+      #     echo "-------------------------"
 
-          patterns=(
-            "linux64/libhm_reader_linux64.so"
-            "linuxa64/libhm_reader_linuxa64.so"
-            "win64/hm_reader_win64.lib"
-            "win64/hm_reader_win64.dll"
-          )
+      #     patterns=(
+      #       "linux64/libhm_reader_linux64.so"
+      #       "linuxa64/libhm_reader_linuxa64.so"
+      #       "win64/hm_reader_win64.lib"
+      #       "win64/hm_reader_win64.dll"
+      #     )
 
-          result_array=$(jf rt search ${JF_OPTIONS} ${{ env.HM_REMOTE_DIR }}/* | grep '"path":' | sed 's/.*"path": "//' | sed 's/",//')
+      #     result_array=$(jf rt search ${JF_OPTIONS} ${{ env.HM_REMOTE_DIR }}/* | grep '"path":' | sed 's/.*"path": "//' | sed 's/",//')
 
-          all_found=true
-          not_found_libs=''
+      #     all_found=true
+      #     not_found_libs=''
 
-          # Loop through each pattern
-          for pattern in "${patterns[@]}"; do
-              # Check if the pattern is present in any line
-              found=false
-              for line in "${result_array[@]}"; do
-                  if echo "$line" | grep -q "$pattern"; then
-                      found=true
-                      break
-                  fi
-              done
+      #     # Loop through each pattern
+      #     for pattern in "${patterns[@]}"; do
+      #         # Check if the pattern is present in any line
+      #         found=false
+      #         for line in "${result_array[@]}"; do
+      #             if echo "$line" | grep -q "$pattern"; then
+      #                 found=true
+      #                 break
+      #             fi
+      #         done
 
-              # If the pattern was not found in any line, mark as not all found
-              if ! $found; then
-                  # echo "Pattern '$pattern' not found in any line."
-                  not_found_libs+="\n${pattern}"
-                  all_found=false
-              # else
-              #     echo "Pattern '$pattern' found."
-              fi
-          done
+      #         # If the pattern was not found in any line, mark as not all found
+      #         if ! $found; then
+      #             # echo "Pattern '$pattern' not found in any line."
+      #             not_found_libs+="\n${pattern}"
+      #             all_found=false
+      #         # else
+      #         #     echo "Pattern '$pattern' found."
+      #         fi
+      #     done
 
-          # Final result check
-          if $all_found; then
-              echo -e "\nAll librarie have been found!"
-              # Set correct end of step status (if not an email will be sent)
-              echo "STATUS_STEP_CHECK_LIBS=1" >> $GITHUB_ENV
-          else
-              echo -e "\nSome librariy pattern has not been found:\n${not_found_libs}"
-              exit 1
-          fi
+      #     # Final result check
+      #     if $all_found; then
+      #         echo -e "\nAll librarie have been found!"
+      #         # Set correct end of step status (if not an email will be sent)
+      #         echo "STATUS_STEP_CHECK_LIBS=1" >> $GITHUB_ENV
+      #     else
+      #         echo -e "\nSome librariy pattern has not been found:\n${not_found_libs}"
+      #         exit 1
+      #     fi
 
-      # Get last git modifications
-      - name: Checkout git sources
-        uses: actions/checkout@v4
-        with:
-          path: ${{ env.WORKDIR }}
-          clean: 'true'
-          lfs: 'true'
-          # ref: 'main'
-          # Use a PAT else the push won't trigger the next workflow
-          token: ${{ env.GIT_PUSH_SERVBOT_PAT }}          
+      # # Get last git modifications
+      # - name: Checkout git sources
+      #   uses: actions/checkout@v4
+      #   with:
+      #     path: ${{ env.WORKDIR }}
+      #     clean: 'true'
+      #     lfs: 'true'
+      #     # ref: 'main'
+      #     # Use a PAT else the push won't trigger the next workflow
+      #     token: ${{ env.GIT_PUSH_SERVBOT_PAT }}          
 
-      - name: Get hm reader libs locally
-        working-directory: ${{ env.WORKDIR }}
-        run: |
-          echo "--------------"
-          echo "Getting HM Reader files"  
-          echo "----------"
+      # - name: Get hm reader libs locally
+      #   working-directory: ${{ env.WORKDIR }}
+      #   run: |
+      #     echo "--------------"
+      #     echo "Getting HM Reader files"  
+      #     echo "----------"
 
-          # Force local branch to point on same commit as remote branch, way to restore a correct env if old push failed before
-          git fetch origin ${BRANCH_NAME}
-          git reset --hard origin/${BRANCH_NAME}
-          echo "-------checkout"
-          git branch && git log --pretty=oneline -n 5
-          echo "-------"          
+      #     # Force local branch to point on same commit as remote branch, way to restore a correct env if old push failed before
+      #     git fetch origin ${BRANCH_NAME}
+      #     git reset --hard origin/${BRANCH_NAME}
+      #     echo "-------checkout"
+      #     git branch && git log --pretty=oneline -n 5
+      #     echo "-------"          
 
-          echo "Current commit id is $GITHUB_SHA"
+      #     echo "Current commit id is $GITHUB_SHA"
 
-          exit
+      #     exit
 
-          # Opensource libs
-          jf rt download ${JF_OPTIONS} --flat=true --recursive --exclusions="*/_com/*" "${{ env.HM_REMOTE_DIR }}/(*)" ${HMREADER_OPENSOURCE_LOCAL_DIR}/{1}
+      #     # Opensource libs
+      #     jf rt download ${JF_OPTIONS} --flat=true --recursive --exclusions="*/_com/*" "${{ env.HM_REMOTE_DIR }}/(*)" ${HMREADER_OPENSOURCE_LOCAL_DIR}/{1}
 
-          # Add new files
-          git config --global user.email "${{ env.GIT_SERVBOT_EMAIL }}"
-          git config --global user.name "${{ env.GIT_SERVBOT_USER }}"
-          git add .
-          git status
+      #     # Add new files
+      #     git config --global user.email "${{ env.GIT_SERVBOT_EMAIL }}"
+      #     git config --global user.name "${{ env.GIT_SERVBOT_USER }}"
+      #     git add .
+      #     git status
 
-          if [[ -n $(git status --porcelain) ]]; then
-            # Set correct end of step status (if not an email will be sent)
-            echo "STATUS_STEP_GET_LIBS=1" >> $GITHUB_ENV
-            echo "GO_PUSH=1" >> $GITHUB_ENV
-          else
-            echo "There are no changes in the repository, abort."
-            exit 1
-          fi
+      #     if [[ -n $(git status --porcelain) ]]; then
+      #       # Set correct end of step status (if not an email will be sent)
+      #       echo "STATUS_STEP_GET_LIBS=1" >> $GITHUB_ENV
+      #       echo "GO_PUSH=1" >> $GITHUB_ENV
+      #     else
+      #       echo "There are no changes in the repository, abort."
+      #       exit 1
+      #     fi
 
-          git commit -m "Update libhm_reader library for OpenRadioss"
+      #     git commit -m "Update libhm_reader library for OpenRadioss"
 
-      - name: Push changes
-        uses: ad-m/github-push-action@master
-        if: ${{ env.GO_PUSH == 1 }} 
-        with:
-          github_token: ${{ env.GIT_PUSH_SERVBOT_PAT }}
-          branch: ${{ github.ref }}     
-          directory: ${{ env.WORKDIR }}    
+      # - name: Push changes
+      #   uses: ad-m/github-push-action@master
+      #   if: ${{ env.GO_PUSH == 1 }} 
+      #   with:
+      #     github_token: ${{ env.GIT_PUSH_SERVBOT_PAT }}
+      #     branch: ${{ github.ref }}     
+      #     directory: ${{ env.WORKDIR }}    
 
-      - name: Set push status
-        working-directory: ${{ env.WORKDIR }}
-        run: |    
-          # Set correct end of step status (if not an email will be sent)
-          echo "STATUS_STEP_PUSH_OR=1" >> $GITHUB_ENV
+      # - name: Set push status
+      #   working-directory: ${{ env.WORKDIR }}
+      #   run: |    
+      #     # Set correct end of step status (if not an email will be sent)
+      #     echo "STATUS_STEP_PUSH_OR=1" >> $GITHUB_ENV
 
       - name: Managing step execution
         if: ${{ always() }}
         run: |
 
-          LOG_PATH="${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}"
-          MAILMSG="The delivery of hm reader libraries into OpenRadioss repository fails.\n\nFind detail in log page ${LOG_PATH}\n\n"
-          CONTINUE=1
+          SUBJECT="[ TEST ] - Error in CI"
+          export HMREADER_TO_EMAIL="mquinzin@altair.com maxime.quinzin@gmail.com"
+          echo -e "Hello" | ${MAIL_COMMAND} -r ${FROM_EMAIL} -s "${SUBJECT}" ${HMREADER_TO_EMAIL}
 
-          echo -e "\n#### STATUS_STEP_CHECK_DELIV_COMMIT ###"
-          if [ "$STATUS_STEP_CHECK_DELIV_COMMIT" = 0 ]
-          then
-            echo -e "Status\t[ \033[31;2;1mFAILED\033[0m ]" 
-            MAILMSG+="$MSG_STEP_CHECK_DELIV_COMMIT\n"
-            CONTINUE=0
-          else
-            echo -e "Status\t[ \033[32;2;1mOK\033[0m ]"
-          fi
+          # LOG_PATH="${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}"
+          # MAILMSG="The delivery of hm reader libraries into OpenRadioss repository fails.\n\nFind detail in log page ${LOG_PATH}\n\n"
+          # CONTINUE=1
 
-          if [ "$CONTINUE" = 1 ]
-          then          
-            echo -e "\n#### STATUS_STEP_CHECK_LIBS ###"
-            if [ "$STATUS_STEP_CHECK_LIBS" = 0 ]
-            then
-              echo -e "Status\t[ \033[31;2;1mFAILED\033[0m ]" 
-              MAILMSG+="$MSG_STEP_CHECK_LIBS\n"
-              CONTINUE=0
-            else
-              echo -e "Status\t[ \033[32;2;1mOK\033[0m ]"
-            fi
-          fi
+          # echo -e "\n#### STATUS_STEP_CHECK_DELIV_COMMIT ###"
+          # if [ "$STATUS_STEP_CHECK_DELIV_COMMIT" = 0 ]
+          # then
+          #   echo -e "Status\t[ \033[31;2;1mFAILED\033[0m ]" 
+          #   MAILMSG+="$MSG_STEP_CHECK_DELIV_COMMIT\n"
+          #   CONTINUE=0
+          # else
+          #   echo -e "Status\t[ \033[32;2;1mOK\033[0m ]"
+          # fi
 
-          if [ "$CONTINUE" = 1 ]
-          then          
-            echo -e "\n#### STATUS_STEP_GET_LIBS ###"
-            if [ "$STATUS_STEP_GET_LIBS" = 0 ]
-            then
-              echo -e "Status\t[ \033[31;2;1mFAILED\033[0m ]" 
-              MAILMSG+="$MSG_STEP_GET_LIBS\n"
-              CONTINUE=0
-            else
-              echo -e "Status\t[ \033[32;2;1mOK\033[0m ]"
-            fi
-          fi
+          # if [ "$CONTINUE" = 1 ]
+          # then          
+          #   echo -e "\n#### STATUS_STEP_CHECK_LIBS ###"
+          #   if [ "$STATUS_STEP_CHECK_LIBS" = 0 ]
+          #   then
+          #     echo -e "Status\t[ \033[31;2;1mFAILED\033[0m ]" 
+          #     MAILMSG+="$MSG_STEP_CHECK_LIBS\n"
+          #     CONTINUE=0
+          #   else
+          #     echo -e "Status\t[ \033[32;2;1mOK\033[0m ]"
+          #   fi
+          # fi
 
-          if [ "$CONTINUE" = 1 ]
-          then          
-            echo -e "\n#### STATUS_STEP_PUSH_OR ###"
-            if [ "$STATUS_STEP_PUSH_OR" = 0 ]
-            then
-              echo -e "Status\t[ \033[31;2;1mFAILED\033[0m ]" 
-              MAILMSG+="$MSG_STEP_PUSH_OR\n"
-              CONTINUE=0
-            else
-              echo -e "Status\t[ \033[32;2;1mOK\033[0m ]"
-            fi
-          fi          
+          # if [ "$CONTINUE" = 1 ]
+          # then          
+          #   echo -e "\n#### STATUS_STEP_GET_LIBS ###"
+          #   if [ "$STATUS_STEP_GET_LIBS" = 0 ]
+          #   then
+          #     echo -e "Status\t[ \033[31;2;1mFAILED\033[0m ]" 
+          #     MAILMSG+="$MSG_STEP_GET_LIBS\n"
+          #     CONTINUE=0
+          #   else
+          #     echo -e "Status\t[ \033[32;2;1mOK\033[0m ]"
+          #   fi
+          # fi
 
-          # Send email 
-          if [ "$CONTINUE" = 0 ] 
-          then
+          # if [ "$CONTINUE" = 1 ]
+          # then          
+          #   echo -e "\n#### STATUS_STEP_PUSH_OR ###"
+          #   if [ "$STATUS_STEP_PUSH_OR" = 0 ]
+          #   then
+          #     echo -e "Status\t[ \033[31;2;1mFAILED\033[0m ]" 
+          #     MAILMSG+="$MSG_STEP_PUSH_OR\n"
+          #     CONTINUE=0
+          #   else
+          #     echo -e "Status\t[ \033[32;2;1mOK\033[0m ]"
+          #   fi
+          # fi          
+
+          # # Send email 
+          # if [ "$CONTINUE" = 0 ] 
+          # then
     
-            # Setting SMTP server (docker host)
-            DOCKER_HOST=`/sbin/ip route|awk '/default/ { print $3 }'`
-            echo "set smtp=smtp://${DOCKER_HOST}:25" >> ${MAIL_CONFIG_FILE}
+          #   # Setting SMTP server (docker host)
+          #   DOCKER_HOST=`/sbin/ip route|awk '/default/ { print $3 }'`
+          #   echo "set smtp=smtp://${DOCKER_HOST}:25" >> ${MAIL_CONFIG_FILE}
 
-            # Print message in log 
-            echo -e $MAILMSG
+          #   # Print message in log 
+          #   echo -e $MAILMSG
 
-            # DEV ONLY #
-            export HMREADER_TO_EMAIL="mquinzin@europe.altair.com"
+          #   # DEV ONLY #
+          #   export HMREADER_TO_EMAIL="mquinzin@europe.altair.com"
 
-            # Send email
-            SUBJECT="[ HMREADER LIBS PUSH on OPENRADIOSS ] - Error in CI"
-            echo -e "${MAILMSG}" | ${MAIL_COMMAND} -r ${FROM_EMAIL} -s "${SUBJECT}" ${HMREADER_TO_EMAIL}
+          #   # Send email
+          #   SUBJECT="[ HMREADER LIBS PUSH on OPENRADIOSS ] - Error in CI"
+          #   echo -e "${MAILMSG}" | ${MAIL_COMMAND} -r ${FROM_EMAIL} -s "${SUBJECT}" ${HMREADER_TO_EMAIL}
 
-            # Exit fail to see it as a failure
-            exit 1
-          fi
+          #   # Exit fail to see it as a failure
+          #   exit 1
+          # fi
