Test windows build

diff --git a/.github/workflows/prmerge_ci_main_testwindows.yml b/.github/workflows/prmerge_ci_main_testwindows.yml
--- a/.github/workflows/prmerge_ci_main_testwindows.yml
+++ b/.github/workflows/prmerge_ci_main_testwindows.yml
@@ -141,10 +141,10 @@ jobs:
               echo -e $MAILMSG; \
 
               # Send email
-              echo -e "$MAILMSG\nThe branch is closed" | Eail -f $FROM_EMAIL -s "Error in Github CI repo ${{ github.repository }} (${{github.sha}})" -r $MAIL_RELAY $TO_EMAIL
+              echo -e "$MAILMSG\nThe branch is closed" | Eail -f $FROM_EMAIL -s "Error in Github CI repo ${{ github.repository }} (${{github.sha}})" -r $MAIL_RELAY $TO_EMAIL; \
 
               # Exit fail to see it as a failure
-              exit 1
+              exit 1; \
 
             else
               echo -e 'Status\t[ \033[32;2;1mOK\033[0m ]'; \
