Test CI merge - Empty repo

diff --git a/.github/workflows/prmerge_ci_sync.yml b/.github/workflows/prmerge_ci_sync.yml
--- a/.github/workflows/prmerge_ci_sync.yml
+++ b/.github/workflows/prmerge_ci_sync.yml
@@ -111,132 +111,131 @@ jobs:
         run: |
           mkdir -p ${{ env.WORKDIR }} $INTEGRATE_WS
           
-      # - name: Run fake sync
-      #   run: |
-      #     echo "Run fake sync : $GITHUB_SERVER_URL/$GITHUB_REPOSITORY"
+      # # - name: Run fake sync
+      # #   run: |
+      # #     echo "Run fake sync : $GITHUB_SERVER_URL/$GITHUB_REPOSITORY"
 
-      # Create a WS to sync git changes on a temporary repo (sync_git_perforce)
-      - name: Create/Update sync_git_perforce workspace
-        working-directory: ${{ env.WORKDIR }}
-        run: |
-          echo $P4PASSWD | p4 login
-          export P4CLIENT=$(echo "${P4USER}_${{ github.repository }}_sync_git_perforce" | tr '/' '_')
-          echo "P4CLIENT=$P4CLIENT" >> $GITHUB_ENV
-          if ! p4 client -o -t $P4CLIENT > /dev/null 2>&1; then 
-            echo "Creating workspace $P4CLIENT (1st time run)"
-            echo "
-          Client: $P4CLIENT
-          Owner:  servbot
-          Root:   $PWD
-          Options:        noallwrite noclobber nocompress unlocked nomodtime normdir
-          SubmitOptions:  submitunchanged
-          LineEnd:        local
-          View:
-            $P4REPOSYNCPERFORCE/... //$P4CLIENT/...
-            -$P4REPOSYNCPERFORCE/.git/... //$P4CLIENT/.git/...
-            -$P4REPOSYNCPERFORCE/.github/... //$P4CLIENT/.github/...
-            -$P4REPOSYNCPERFORCE/.gitattributes //$P4CLIENT/.gitattributes
-            -$P4REPOSYNCPERFORCE/.p4config //$P4CLIENT/.p4config
-            -$P4REPOSYNCPERFORCE/extlib/... //$P4CLIENT/extlib/...
-            " | p4 client -i;
-          fi
-
-          # Clean possible previous pending changelists 
-          p4 revert ./...
-          for cl in `p4 changes -c $P4CLIENT -s pending | grep "\[ GIT\(LAB\|HUB\)\? INTEG \]" | awk -F' ' '{print $2}' | sort -n`
-          do 
-            echo "Removing old pending CL $cl"
-            p4 change -d $cl
-          done
-
-          p4 sync
-
-          export SCRIPT_OPT=''
-
-          # In case of first run we won't find last known commit so we force script 
-          # Variable RUN_FIRST_TIME must be set to run_1 at this precise moment
-          if [ "$RUN_FIRST_TIME" = "run_1" ]
-          then 
-            SCRIPT_OPT='--force_sync'
-          else
-            CL=`p4 changes -c $P4CLIENT -s submitted | grep "\[ GIT\(LAB\|HUB\)\? INTEG \]" | head -1 |awk -F' ' '{print $2}'`
-            RET=`p4 describe $CL | head -3 | tail -1 | sed -e "s/^.*\[ GIT\(LAB\|HUB\)\? INTEG \] //;s/ .*$//"`
-
-            if [ -z $RET ] || [ "$RET" = "" ]
-            then 
-              exit 1
-            else 
-              SCRIPT_OPT="--perforce_last_commit $RET"; fi
-          fi
-
-          echo "SCRIPT_OPT : $SCRIPT_OPT"
-
-          echo "sync_option=$SCRIPT_OPT" >> $GITHUB_ENV
-          echo -e "P4USER=$P4USER\nP4PORT=$P4PORT\nP4CLIENT=$P4CLIENT" > .p4config
-
-          # Set correct end of step status (if not an email will be sent)
-          echo "STATUS_STEP_PERFORCE_LAST_KNOWN_GIT_COMMIT=1" >> $GITHUB_ENV
-
-      # Get all unsynced commit since last good one
-      # If we never meet the last known commit on perforce we abort, that could mean there are more commits to into account
-      # At WS creation we use the dedicated --force_sync option to accept submiting event if perforce_last_commit has not been found
-      # so if this specific case fails, think to delete perforce client before re-running
-      - name: Get all unsynced commit since last good one
-        run: |
-          sync_git_2_perforce.py \
-            --git_api_url ${{ github.api_url }} \
-            --git_repo ${{ github.repository }} \
-            --git_user $SERVBOT_USER \
-            --git_token $SERVBOT_PAT \
-            --interval_check "${{ env.DATE_MIN_CHECK_COMMITS }}" \
-            --output_file ${{ env.COMMIT_LIST_FILE }} \
-            $sync_option \
-            --current_commit ${{github.sha}} 
-
-      # # Create/Upgrade local git repo
-      # - uses: actions/checkout@v3
-      #   with:
-      #     path: ${{ env.WORKDIR }}
-      #     clean: 'false'
-      #     lfs: 'true'
-      # - name: Unshallow the git log, else we won't be able to checkout commits 
+      # # Create a WS to sync git changes on a temporary repo (sync_git_perforce)
+      # - name: Create/Update sync_git_perforce workspace
       #   working-directory: ${{ env.WORKDIR }}
-      #   run: git fetch --unshallow
+      #   run: |
+      #     echo $P4PASSWD | p4 login
+      #     export P4CLIENT=$(echo "${P4USER}_${{ github.repository }}_sync_git_perforce" | tr '/' '_')
+      #     echo "P4CLIENT=$P4CLIENT" >> $GITHUB_ENV
+      #     if ! p4 client -o -t $P4CLIENT > /dev/null 2>&1; then 
+      #       echo "Creating workspace $P4CLIENT (1st time run)"
+      #       echo "
+      #     Client: $P4CLIENT
+      #     Owner:  servbot
+      #     Root:   $PWD
+      #     Options:        noallwrite noclobber nocompress unlocked nomodtime normdir
+      #     SubmitOptions:  submitunchanged
+      #     LineEnd:        local
+      #     View:
+      #       $P4REPOSYNCPERFORCE/... //$P4CLIENT/...
+      #       -$P4REPOSYNCPERFORCE/.git/... //$P4CLIENT/.git/...
+      #       -$P4REPOSYNCPERFORCE/.github/... //$P4CLIENT/.github/...
+      #       -$P4REPOSYNCPERFORCE/.gitattributes //$P4CLIENT/.gitattributes
+      #       -$P4REPOSYNCPERFORCE/.p4config //$P4CLIENT/.p4config
+      #       -$P4REPOSYNCPERFORCE/extlib/... //$P4CLIENT/extlib/...
+      #       " | p4 client -i;
+      #     fi
 
-      ## For each commit found: get git files, p4 reconcile and submit
-      # If some file are still opened after submit, abort
-      - name: Upgrade perforce for each git commit found
-        working-directory: ${{ env.WORKDIR }}
-        run: |
-          git config --global advice.detachedHead false
-          git fetch
+      #     # Clean possible previous pending changelists 
+      #     p4 revert ./...
+      #     for cl in `p4 changes -c $P4CLIENT -s pending | grep "\[ GIT\(LAB\|HUB\)\? INTEG \]" | awk -F' ' '{print $2}' | sort -n`
+      #     do 
+      #       echo "Removing old pending CL $cl"
+      #       p4 change -d $cl
+      #     done
 
-          # We don't want extlib to be synced
-          rm -rf extlib
-          ls -ls
+      #     p4 sync
 
-          while read LINE
-          do
-            IFS='||'; arrIN=($LINE); unset IFS;
-            message="[ GITHUB INTEG ] ${arrIN[0]} - ${arrIN[2]} - ${arrIN[4]}"
-            echo "---------------------------------"
-            echo "-- ${arrIN[0]} --"
-            echo "---------------------------------"
-            echo "INFO_STEP_SUBMIT_TMP_SYNC_REPO=${arrIN[0]}" >> $GITHUB_ENV
-            git checkout ${arrIN[0]}
-            #p4 status
-            p4 reconcile
-            opened_files_nb=$(p4 opened -c default | wc -l)
-            #echo "OPENED : ${opened_files_nb}"
-            if [ ${opened_files_nb} -gt 0 ]
-            then 
-              p4 submit -d "${message}"
-            fi
+      #     export SCRIPT_OPT=''
 
-          done < ${{ env.COMMIT_LIST_FILE }}
+      #     # In case of first run we won't find last known commit so we force script 
+      #     # Variable RUN_FIRST_TIME must be set to run_1 at this precise moment
+      #     if [ "$RUN_FIRST_TIME" = "run_1" ]
+      #     then 
+      #       SCRIPT_OPT='--force_sync'
+      #     else
+      #       CL=`p4 changes -c $P4CLIENT -s submitted | grep "\[ GIT\(LAB\|HUB\)\? INTEG \]" | head -1 |awk -F' ' '{print $2}'`
+      #       RET=`p4 describe $CL | head -3 | tail -1 | sed -e "s/^.*\[ GIT\(LAB\|HUB\)\? INTEG \] //;s/ .*$//"`
 
-          # Set correct end of step status (if not an email will be sent)
-          echo "STATUS_STEP_SUBMIT_TMP_SYNC_REPO=1" >> $GITHUB_ENV
+      #       if [ -z $RET ] || [ "$RET" = "" ]
+      #       then 
+      #         exit 1
+      #       else 
+      #         SCRIPT_OPT="--perforce_last_commit $RET"; fi
+      #     fi
+
+      #     echo "SCRIPT_OPT : $SCRIPT_OPT"
+
+      #     echo "sync_option=$SCRIPT_OPT" >> $GITHUB_ENV
+      #     echo -e "P4USER=$P4USER\nP4PORT=$P4PORT\nP4CLIENT=$P4CLIENT" > .p4config
+
+      #     # Set correct end of step status (if not an email will be sent)
+      #     echo "STATUS_STEP_PERFORCE_LAST_KNOWN_GIT_COMMIT=1" >> $GITHUB_ENV
+
+      # # Get all unsynced commit since last good one
+      # # If we never meet the last known commit on perforce we abort, that could mean there are more commits to into account
+      # # At WS creation we use the dedicated --force_sync option to accept submiting event if perforce_last_commit has not been found
+      # # so if this specific case fails, think to delete perforce client before re-running
+      # - name: Get all unsynced commit since last good one
+      #   run: |
+      #     sync_git_2_perforce.py \
+      #       --git_api_url ${{ github.api_url }} \
+      #       --git_repo ${{ github.repository }} \
+      #       --git_user $SERVBOT_USER \
+      #       --git_token $SERVBOT_PAT \
+      #       --interval_check "${{ env.DATE_MIN_CHECK_COMMITS }}" \
+      #       --output_file ${{ env.COMMIT_LIST_FILE }} \
+      #       $sync_option \
+      #       --current_commit ${{github.sha}} 
+
+      # # # Create/Upgrade local git repo
+      # # - uses: actions/checkout@v3
+      # #   with:
+      # #     path: ${{ env.WORKDIR }}
+      # #     clean: 'false'
+      # #     lfs: 'true'
+      # # - name: Unshallow the git log, else we won't be able to checkout commits 
+      # #   working-directory: ${{ env.WORKDIR }}
+      # #   run: git fetch --unshallow
+
+      # ## For each commit found: get git files, p4 reconcile and submit
+      # # If some file are still opened after submit, abort
+      # - name: Upgrade perforce for each git commit found
+      #   working-directory: ${{ env.WORKDIR }}
+      #   run: |
+      #     git config --global advice.detachedHead false
+
+      #     # We don't want extlib to be synced
+      #     rm -rf extlib
+      #     ls -ls
+
+      #     while read LINE
+      #     do
+      #       IFS='||'; arrIN=($LINE); unset IFS;
+      #       message="[ GITHUB INTEG ] ${arrIN[0]} - ${arrIN[2]} - ${arrIN[4]}"
+      #       echo "---------------------------------"
+      #       echo "-- ${arrIN[0]} --"
+      #       echo "---------------------------------"
+      #       echo "INFO_STEP_SUBMIT_TMP_SYNC_REPO=${arrIN[0]}" >> $GITHUB_ENV
+      #       git checkout ${arrIN[0]}
+      #       #p4 status
+      #       p4 reconcile
+      #       opened_files_nb=$(p4 opened -c default | wc -l)
+      #       #echo "OPENED : ${opened_files_nb}"
+      #       if [ ${opened_files_nb} -gt 0 ]
+      #       then 
+      #         p4 submit -d "${message}"
+      #       fi
+
+      #     done < ${{ env.COMMIT_LIST_FILE }}
+
+      #     # Set correct end of step status (if not an email will be sent)
+      #     echo "STATUS_STEP_SUBMIT_TMP_SYNC_REPO=1" >> $GITHUB_ENV
 
 
       # # Create a WS to integration (and merge on the fly) the temporary repo (sync_git_perforce) to the final destination
