Test CI merge - GITHUB/LAB/<> grep

diff --git a/.github/workflows/prmerge_ci_sync.yml b/.github/workflows/prmerge_ci_sync.yml
--- a/.github/workflows/prmerge_ci_sync.yml
+++ b/.github/workflows/prmerge_ci_sync.yml
@@ -298,43 +298,45 @@ jobs:
 
           else
 
-            echo "p4 changes -l -s submitted -m 1000 $P4REPOPERFORCE/... | grep \"^\s*\[ GIT INTEG \]\" | head -n 1 | sed -e \"s/^.*\[ GIT INTEG \] //;s/ .*$//\""
-            echo "p4 changes -s submitted -m 1000 $P4REPOSYNCPERFORCE/... | grep -B 10000 \"GIT INTEG.*\s*$LAST_KNOW_INTEG_COMMIT_TRUNCATED\" | head -n-1 | awk -F' ' '{print $2}' | sort -n"
+            echo "p4 changes -l -s submitted -m 1000 $P4REPOPERFORCE/... | grep \"^\s*\[ GIT\(LAB\|HUB\)\? INTEG \]" | head -n 1 | sed -e \"s/^.*\[ GIT\(LAB\|HUB\)\? INTEG \] //;s/ .*$//\""
+            echo "p4 changes -s submitted -m 1000 $P4REPOSYNCPERFORCE/... | grep -B 10000 \"GIT\(LAB\|HUB\)\? INTEG.*\s*$LAST_KNOW_INTEG_COMMIT_TRUNCATED\" | head -n-1 | awk -F' ' '{print $2}' | sort -n"
 
             # # Getting the last known integrated commit
-            # export LAST_KNOW_INTEG_COMMIT=`p4 changes -l -s submitted -m 1000 $P4REPOPERFORCE/... | grep "^\s*\[ GIT INTEG \]" | head -n 1 | sed -e "s/^.*\[ GIT INTEG \] //;s/ .*$//"`
-            # export LAST_KNOW_INTEG_COMMIT_TRUNCATED=$(echo $LAST_KNOW_INTEG_COMMIT | cut -c -16)
+            # export LAST_KNOW_INTEG_COMMIT=`p4 changes -l -s submitted -m 1000 $P4REPOPERFORCE/... | grep "^\s*\[ GIT\(LAB\|HUB\)\? INTEG \]" | head -n 1 | sed -e "s/^.*\[ GIT\(LAB\|HUB\)\? INTEG \] //;s/ .*$//"`
+            # export LAST_KNOW_INTEG_COMMIT_TRUNCATED=$(echo $LAST_KNOW_INTEG_COMMIT | cut -c -14)
 
-            # # Getting all not integrated changelist (=all until last know commit)
-            # if [ ! -z "$LAST_KNOW_INTEG_COMMIT_TRUNCATED" ]
-            # then 
+            echo "LAST_KNOW_INTEG_COMMIT_TRUNCATED is $LAST_KNOW_INTEG_COMMIT_TRUNCATED"
 
-            #   # Set correct end of step status (if not an email will be sent)
-            #   echo "STATUS_STEP_PERFORCE_LAST_KNOWN_INTEGRATED_COMMIT=1" >> $GITHUB_ENV
+            # Getting all not integrated changelist (=all until last know commit)
+            if [ ! -z "$LAST_KNOW_INTEG_COMMIT_TRUNCATED" ]
+            then 
 
-            #   for changelist in `p4 changes -s submitted -m 1000 $P4REPOSYNCPERFORCE/... | grep -B 10000 "GIT INTEG.*\s*$LAST_KNOW_INTEG_COMMIT_TRUNCATED" | head -n-1 | awk -F' ' '{print $2}' | sort -n`
-            #   do 
-            #     echo "---------------------------------"
-            #     echo "-- $changelist --"
-            #     echo "---------------------------------"
+              # Set correct end of step status (if not an email will be sent)
+              echo "STATUS_STEP_PERFORCE_LAST_KNOWN_INTEGRATED_COMMIT=1" >> $GITHUB_ENV
 
-            #     echo "INFO_STEP_SUBMIT_INTEGRATE_REPO=$changelist" >> $GITHUB_ENV
+              for changelist in `p4 changes -s submitted -m 1000 $P4REPOSYNCPERFORCE/... | grep -B 10000 "GIT\(LAB\|HUB\)\? INTEG.*\s*$LAST_KNOW_INTEG_COMMIT_TRUNCATED" | head -n-1 | awk -F' ' '{print $2}' | sort -n`
+              do 
+                echo "---------------------------------"
+                echo "-- $changelist --"
+                echo "---------------------------------"
 
-            #     p4 integrate $P4REPOSYNCPERFORCE/...@$changelist,@$changelist $P4REPOPERFORCE/...
-            #     p4 resolve -am
-            #     p4_description=`p4 -Ztag -F %Description% change -o $changelist`
-            #     p4 submit -d "$p4_description"
+                echo "INFO_STEP_SUBMIT_INTEGRATE_REPO=$changelist" >> $GITHUB_ENV
 
-            #   done
+                # p4 integrate $P4REPOSYNCPERFORCE/...@$changelist,@$changelist $P4REPOPERFORCE/...
+                # p4 resolve -am
+                # p4_description=`p4 -Ztag -F %Description% change -o $changelist`
+                # p4 submit -d "$p4_description"
 
-            #   # Set correct end of step status (if not an email will be sent)
-            #   echo "STATUS_STEP_SUBMIT_INTEGRATE_REPO=1" >> $GITHUB_ENV
+              done
 
-            # else 
-            #   # Exit 1 not found LAST_KNOW_INTEG_COMMIT
-            #   # echo "Error cannot find a last known integrate commit in $P4REPOPERFORCE repository"
-            #   exit 1
-            # fi
+              # Set correct end of step status (if not an email will be sent)
+              echo "STATUS_STEP_SUBMIT_INTEGRATE_REPO=1" >> $GITHUB_ENV
+
+            else 
+              # Exit 1 not found LAST_KNOW_INTEG_COMMIT
+              # echo "Error cannot find a last known integrate commit in $P4REPOPERFORCE repository"
+              exit 1
+            fi
 
           fi
 
