Use ifx binary name

diff --git a/.github/workflows/prmerge_ci_main.yml b/.github/workflows/prmerge_ci_main.yml
--- a/.github/workflows/prmerge_ci_main.yml
+++ b/.github/workflows/prmerge_ci_main.yml
@@ -592,178 +592,178 @@ jobs:
   #       if: ${{ always() && env.CLOSE_BRANCH == 1 && steps.close_branch_qa.outputs.status != 200 }} 
 
 
-  build_windows_no_container:
-    if: ${{ github.repository_owner == 'OpenRadioss' }}
-    # runs-on: ["${{ matrix.build }}","prmerge_ci"]
-    runs-on: ["${{ matrix.build }}","dev_pmci"]
+  # build_windows_no_container:
+  #   if: ${{ github.repository_owner == 'OpenRadioss' }}
+  #   # runs-on: ["${{ matrix.build }}","prmerge_ci"]
+  #   runs-on: ["${{ matrix.build }}","dev_pmci"]
 
-    env:
-      BUILD_NB_THREAD: 2
-      STATUS_BUILD: 0
-      SERVBOT_PAT: ${{ secrets.SERVBOT_PAT }}
-      CLOSE_BRANCH: 0
+  #   env:
+  #     BUILD_NB_THREAD: 2
+  #     STATUS_BUILD: 0
+  #     SERVBOT_PAT: ${{ secrets.SERVBOT_PAT }}
+  #     CLOSE_BRANCH: 0
 
-    strategy:
-      # If one job fails others are canceled
-      fail-fast: true
-      matrix:
-        include:
-          - build: starter_win64
-            precision: dp
-            os: win64
-            binary: starter
+  #   strategy:
+  #     # If one job fails others are canceled
+  #     fail-fast: true
+  #     matrix:
+  #       include:
+  #         - build: starter_win64
+  #           precision: dp
+  #           os: win64
+  #           binary: starter
 
-          # - build: starter_win64_sp
-          #   precision: sp
-          #   os: win64
-          #   binary: starter
+  #         # - build: starter_win64_sp
+  #         #   precision: sp
+  #         #   os: win64
+  #         #   binary: starter
 
-          - build: engine_win64_impi
-            precision: dp
-            os: win64
-            binary: engine
-            mpi: impi
+  #         - build: engine_win64_impi
+  #           precision: dp
+  #           os: win64
+  #           binary: engine
+  #           mpi: impi
 
-          # - build: engine_win64_impi_sp
-          #   precision: sp
-          #   os: win64
-          #   binary: engine
-          #   mpi: impi
+  #         # - build: engine_win64_impi_sp
+  #         #   precision: sp
+  #         #   os: win64
+  #         #   binary: engine
+  #         #   mpi: impi
 
-          # - build: engine_win64
-          #   precision: dp
-          #   os: win64
-          #   binary: engine
+  #         # - build: engine_win64
+  #         #   precision: dp
+  #         #   os: win64
+  #         #   binary: engine
 
-          # - build: engine_win64_sp
-          #   precision: sp
-          #   os: win64
-          #   binary: engine
+  #         # - build: engine_win64_sp
+  #         #   precision: sp
+  #         #   os: win64
+  #         #   binary: engine
 
-    steps:
+  #   steps:
 
-      # Set the working dir suffixed with branch name
-      - name: Set workdir 
-        run: |
-          if ([string]::IsNullOrEmpty($env:GITHUB_BASE_REF)) {
-            Add-Content -Path $env:GITHUB_ENV -Value "WORKDIR=$env:GITHUB_REF_NAME"
-          } 
-          else {
-            Add-Content -Path $env:GITHUB_ENV -Value "WORKDIR=$env:GITHUB_BASE_REF"
-          }          
+  #     # Set the working dir suffixed with branch name
+  #     - name: Set workdir 
+  #       run: |
+  #         if ([string]::IsNullOrEmpty($env:GITHUB_BASE_REF)) {
+  #           Add-Content -Path $env:GITHUB_ENV -Value "WORKDIR=$env:GITHUB_REF_NAME"
+  #         } 
+  #         else {
+  #           Add-Content -Path $env:GITHUB_ENV -Value "WORKDIR=$env:GITHUB_BASE_REF"
+  #         }          
 
-      - name: Create branch oriented WS directory & integration WS (WIN64)
-        run: |
-          $dir2create = "$env:WORKDIR"
-          if (-not (Test-Path -Path $dir2create)) {
-            New-Item -Path $dir2create -ItemType "Directory"
-          }
+  #     - name: Create branch oriented WS directory & integration WS (WIN64)
+  #       run: |
+  #         $dir2create = "$env:WORKDIR"
+  #         if (-not (Test-Path -Path $dir2create)) {
+  #           New-Item -Path $dir2create -ItemType "Directory"
+  #         }
 
-      - name: Clean local exe dir
-        working-directory: ${{ env.WORKDIR }}
-        run: |
-          $dir2remove = "exec"
-          if (Test-Path -Path $dir2remove) {
-            Remove-Item -Path $dir2remove -Recurse -Force
-          }
+  #     - name: Clean local exe dir
+  #       working-directory: ${{ env.WORKDIR }}
+  #       run: |
+  #         $dir2remove = "exec"
+  #         if (Test-Path -Path $dir2remove) {
+  #           Remove-Item -Path $dir2remove -Recurse -Force
+  #         }
 
-      # Get last git modifications, don't clean before (way to keep persistent obj files)
-      - name: Checkout git sources
-        uses: actions/checkout@v4
-        with:
-          path: ${{ env.WORKDIR }}
-          clean: 'false'
-          lfs: 'true'
+  #     # Get last git modifications, don't clean before (way to keep persistent obj files)
+  #     - name: Checkout git sources
+  #       uses: actions/checkout@v4
+  #       with:
+  #         path: ${{ env.WORKDIR }}
+  #         clean: 'false'
+  #         lfs: 'true'
 
-      - name: Running builds
-        working-directory: ${{ env.WORKDIR }}
-        run: |
-          cd ${{ matrix.binary }}
-          @"
-          @echo off
-          call "C:\Program Files (x86)\Intel\oneAPI\setvars.bat" intel64 vs2019
-          ifx --version
-          cmake --version
-          ninja --version
-          if not '${{ matrix.mpi }}'=='' (
-            set mpi_opts=-mpi=${{ matrix.mpi }}
-          )   
-          echo =========================================
-          echo --  BUILD ${{ matrix.build }} --
-          echo =========================================
-          .\build_windows.bat -release -arch=${{ matrix.os }}_ifx -prec=${{ matrix.precision }} -nt=$env:BUILD_NB_THREAD %mpi_opts%
-          "@ -replace "'", '"' | Out-File -FilePath myrun.bat -Encoding ASCII
-          cmd /c .\myrun.bat    
-          cd ..
-          $directoryPath = "exec"
-          if (Test-Path -Path $directoryPath) {
-              $files = Get-ChildItem -Path $directoryPath
-              if ($files.Count -eq 0) {
-                  Write-Output "The directory is empty."
-                  exit 1
-              } else {
-                  # Display the contents of the directory
-                  $files | ForEach-Object { Write-Output $_.FullName }
-              }
-          } else {
-              Write-Output "The directory does not exist."
-              exit 1
-          }
-          Add-Content -Path $env:GITHUB_ENV -Value "STATUS_BUILD=1"
+  #     - name: Running builds
+  #       working-directory: ${{ env.WORKDIR }}
+  #       run: |
+  #         cd ${{ matrix.binary }}
+  #         @"
+  #         @echo off
+  #         call "C:\Program Files (x86)\Intel\oneAPI\setvars.bat" intel64 vs2019
+  #         ifx --version
+  #         cmake --version
+  #         ninja --version
+  #         if not '${{ matrix.mpi }}'=='' (
+  #           set mpi_opts=-mpi=${{ matrix.mpi }}
+  #         )   
+  #         echo =========================================
+  #         echo --  BUILD ${{ matrix.build }} --
+  #         echo =========================================
+  #         .\build_windows.bat -release -arch=${{ matrix.os }}_ifx -prec=${{ matrix.precision }} -nt=$env:BUILD_NB_THREAD %mpi_opts%
+  #         "@ -replace "'", '"' | Out-File -FilePath myrun.bat -Encoding ASCII
+  #         cmd /c .\myrun.bat    
+  #         cd ..
+  #         $directoryPath = "exec"
+  #         if (Test-Path -Path $directoryPath) {
+  #             $files = Get-ChildItem -Path $directoryPath
+  #             if ($files.Count -eq 0) {
+  #                 Write-Output "The directory is empty."
+  #                 exit 1
+  #             } else {
+  #                 # Display the contents of the directory
+  #                 $files | ForEach-Object { Write-Output $_.FullName }
+  #             }
+  #         } else {
+  #             Write-Output "The directory does not exist."
+  #             exit 1
+  #         }
+  #         Add-Content -Path $env:GITHUB_ENV -Value "STATUS_BUILD=1"
 
-      - name: Managing step execution
-        if: ${{ always() }}
-        run: |
-          $MAILMSG = "Some error(s) has(ve) been raised during workflow execution:`r`n`r`n"
-          Write-Output "`r`n#### STATUS_STEP_BUILD ${{ matrix.build }} ($env:STATUS_BUILD) ###"
-          if ($env:STATUS_BUILD -eq 0) {
-            Write-Output "Status`t[ $([char]27)[31;2;1mFAILED$([char]27)[0m ]"
-            $MAILMSG += "The build ${{ matrix.build }} has failed `r`n"
-            Add-Content -Path $env:GITHUB_ENV -Value "CLOSE_BRANCH=1"
-            Send-MailMessage -SmtpServer $env:MAIL_RELAY -From $env:FROM_EMAIL -To $env:TO_EMAIL -Subject "Error in Github CI repo ${{ github.repository }} (${{github.sha}})" -Body $MAILMSG -Port 25
-            exit 1
-          }
-          else {
-            Write-Output "Status`t[ $([char]27)[32;2;1mOK$([char]27)[0m ]"
-          }
+  #     - name: Managing step execution
+  #       if: ${{ always() }}
+  #       run: |
+  #         $MAILMSG = "Some error(s) has(ve) been raised during workflow execution:`r`n`r`n"
+  #         Write-Output "`r`n#### STATUS_STEP_BUILD ${{ matrix.build }} ($env:STATUS_BUILD) ###"
+  #         if ($env:STATUS_BUILD -eq 0) {
+  #           Write-Output "Status`t[ $([char]27)[31;2;1mFAILED$([char]27)[0m ]"
+  #           $MAILMSG += "The build ${{ matrix.build }} has failed `r`n"
+  #           Add-Content -Path $env:GITHUB_ENV -Value "CLOSE_BRANCH=1"
+  #           Send-MailMessage -SmtpServer $env:MAIL_RELAY -From $env:FROM_EMAIL -To $env:TO_EMAIL -Subject "Error in Github CI repo ${{ github.repository }} (${{github.sha}})" -Body $MAILMSG -Port 25
+  #           exit 1
+  #         }
+  #         else {
+  #           Write-Output "Status`t[ $([char]27)[32;2;1mOK$([char]27)[0m ]"
+  #         }
 
-      # Upload artifact (since V4 we can't upload artifact using the same name, each one must be unique)
-      - name: Upload built artifacts
-        uses: actions/upload-artifact@v4
-        with:
-          name: bins-${{ matrix.os }}-${{ matrix.precision }}-${{ matrix.build }}
-          path: ${{ env.WORKDIR }}/exec
-        if: ${{ env.CLOSE_BRANCH == 0 }}           
+  #     # Upload artifact (since V4 we can't upload artifact using the same name, each one must be unique)
+  #     - name: Upload built artifacts
+  #       uses: actions/upload-artifact@v4
+  #       with:
+  #         name: bins-${{ matrix.os }}-${{ matrix.precision }}-${{ matrix.build }}
+  #         path: ${{ env.WORKDIR }}/exec
+  #       if: ${{ env.CLOSE_BRANCH == 0 }}           
 
-      # Close the branch (= restrict push to team devopsadmins) if needed
-      # Owner is not mandatory here ... PAT is sufficient ??? seems that as servbot has permissions on this repo so his PAT is sufficient ...
-      - name: Close the branch if errors
-        uses: octokit/request-action@v2.x
-        id: close_branch_build
-        env:
-          GITHUB_TOKEN: ${{ env.SERVBOT_PAT }}
-          REQUEST_BODY: "['${{ env.TEAM_RESTRICTIVE_CLOSED_BRANCH}}']"
-        with:
-          route: PUT /repos/${{ github.repository }}/branches/main/protection/restrictions/teams
-          data: ${{ env.REQUEST_BODY }}
-        if: ${{ always() && env.CLOSE_BRANCH == 1 }}         
+  #     # Close the branch (= restrict push to team devopsadmins) if needed
+  #     # Owner is not mandatory here ... PAT is sufficient ??? seems that as servbot has permissions on this repo so his PAT is sufficient ...
+  #     - name: Close the branch if errors
+  #       uses: octokit/request-action@v2.x
+  #       id: close_branch_build
+  #       env:
+  #         GITHUB_TOKEN: ${{ env.SERVBOT_PAT }}
+  #         REQUEST_BODY: "['${{ env.TEAM_RESTRICTIVE_CLOSED_BRANCH}}']"
+  #       with:
+  #         route: PUT /repos/${{ github.repository }}/branches/main/protection/restrictions/teams
+  #         data: ${{ env.REQUEST_BODY }}
+  #       if: ${{ always() && env.CLOSE_BRANCH == 1 }}         
 
-      # If the closing went wrong we send an email
-      - name: "Check result of closing branch and warn if it fails"
-        run: |
-          $MAILMSG = "Some error(s) has(ve) been raised during workflow execution:`r`n`r`n"
-          $MAILMSG += "A branch closing is needed but has failed`r`n`r`n"
-          $MAILMSG += "Return status API is : ${{ steps.close_branch_build.outputs.status }}`r`n`r`n"
-          $MAILMSG += "Check more detailed datas in CI logs`r`n"
-          Write-Output "`r`nClose return API is : ${{ steps.close_branch_build.outputs.status }} / ${{ steps.close_branch_build.outputs.data }}";
-          Send-MailMessage -SmtpServer $env:MAIL_RELAY -From $env:FROM_EMAIL -To $env:TO_EMAIL -Subject "Error in Github CI repo ${{ github.repository }} (${{github.sha}}) on closing branch" -Body $MAILMSG -Port 25
-          exit 1
-        if: ${{ always() && env.CLOSE_BRANCH == 1 && steps.close_branch_build.outputs.status != 200 }} 
+  #     # If the closing went wrong we send an email
+  #     - name: "Check result of closing branch and warn if it fails"
+  #       run: |
+  #         $MAILMSG = "Some error(s) has(ve) been raised during workflow execution:`r`n`r`n"
+  #         $MAILMSG += "A branch closing is needed but has failed`r`n`r`n"
+  #         $MAILMSG += "Return status API is : ${{ steps.close_branch_build.outputs.status }}`r`n`r`n"
+  #         $MAILMSG += "Check more detailed datas in CI logs`r`n"
+  #         Write-Output "`r`nClose return API is : ${{ steps.close_branch_build.outputs.status }} / ${{ steps.close_branch_build.outputs.data }}";
+  #         Send-MailMessage -SmtpServer $env:MAIL_RELAY -From $env:FROM_EMAIL -To $env:TO_EMAIL -Subject "Error in Github CI repo ${{ github.repository }} (${{github.sha}}) on closing branch" -Body $MAILMSG -Port 25
+  #         exit 1
+  #       if: ${{ always() && env.CLOSE_BRANCH == 1 && steps.close_branch_build.outputs.status != 200 }} 
 
 
   qa_windows_no_container:
 
-    needs: build_windows_no_container
+    # needs: build_windows_no_container
     # runs-on: ["qa_${{ matrix.os }}","prmerge_ci"]
     runs-on: ["qa_${{ matrix.os }}","dev_pmci"]
 
@@ -857,7 +857,7 @@ jobs:
           rm -f QA.summary;
           export PATH=${{ env.hm_reader_extlib }}/${{ matrix.os }}:$PATH;
           export PATH=${{ env.oneapi_exlib }}/${{ matrix.os }}:$PATH;
-          cmd=\"./or_qa_script ../../exec/engine_${{ matrix.os }}_${{ env.mpi }}${precision_ext} 1.0 --env:RAD_CFG_PATH=${{ env.hm_reader_cfgfiles }} --system_run --env:KMP_STACKSIZE=400m --exec_script_args='mpiexec -np ${{ env.QA_NB_PROC }}' --env:OMP_NUM_THREADS=${{ env.QA_NB_THREAD }} --output_failures_stdout --xtra_args='--timeoutscript=${{ env.QA_TIMEOUT_PER_TEST_WIN }}' \";
+          cmd=\"./or_qa_script ../../exec/engine_${{ matrix.os }}_ifx_${{ env.mpi }}${precision_ext} 1.0 --env:RAD_CFG_PATH=${{ env.hm_reader_cfgfiles }} --system_run --env:KMP_STACKSIZE=400m --exec_script_args='mpiexec -np ${{ env.QA_NB_PROC }}' --env:OMP_NUM_THREADS=${{ env.QA_NB_THREAD }} --output_failures_stdout --xtra_args='--timeoutscript=${{ env.QA_TIMEOUT_PER_TEST_WIN }}' \";
           echo \"=========================================\";
           echo \"--  QA ${{ matrix.os }}_${{ matrix.precision }} --\"; 
           echo \"--  $cmd --\";   
