Build anim to vtk tools

diff --git a/.github/workflows/prmerge_ci_main.yml b/.github/workflows/prmerge_ci_main.yml
--- a/.github/workflows/prmerge_ci_main.yml
+++ b/.github/workflows/prmerge_ci_main.yml
@@ -15,6 +15,84 @@ env:
 
 jobs:
 
+  build_tools:
+    if: ${{ github.repository_owner == 'OpenRadioss' }}
+    # DEV ONLY # runs-on: ["${{ matrix.os }}","dev_pmci"]
+    runs-on: ["${{ matrix.os }}","dev_pmci"]
+    # runs-on: ["${{ matrix.os }}","prmerge_ci"]
+    container: 
+      image: fr-qafactorydev.europe.altair.com/build-linux64_gf:ompi411
+      credentials: 
+        username: ${{secrets.DOCKER_REGISTRY_USER}}
+        password: ${{secrets.DOCKER_REGISTRY_PASSWD}}
+      volumes: 
+        - /etc/localtime:/etc/localtime:ro
+
+    env:
+
+    strategy:
+      # If one job fails others continue (tools build & delivery is not blocking no blocker)
+      fail-fast: false
+      matrix:
+        include:
+          - os: linux64
+
+    steps:
+
+      # Set the working dir suffixed with branch name
+      - uses: haya14busa/action-cond@v1
+        id: set_workdir
+        with:
+          cond: ${{ github.base_ref == '' }}
+          if_true: ${{github.ref_name}}
+          if_false: ${{github.base_ref}}
+
+      - name: Create branch oriented WS directory & integration WS
+        run: |
+          mkdir -p ${{ steps.set_workdir.outputs.value }}
+
+      - name: Clean local exe dir
+        working-directory: ${{ steps.set_workdir.outputs.value }}
+        run: |
+          rm -rf exec
+          md5sum exec/* || echo "Nothing in exec/" 
+
+      # Get last git modifications, don't clean before (way to keep persistent obj files)
+      - uses: actions/checkout@v2
+        with:
+          path: ${{ steps.set_workdir.outputs.value }}
+          clean: 'false'
+          lfs: 'true'
+
+      - name: Running builds
+        working-directory: ${{ steps.set_workdir.outputs.value }}
+        run: |
+          mkdir exec
+
+          cmd="./build.bash"
+          echo "========================================="
+          echo "--  BUILD tools for anim_to_vtk (${{ matrix.os }}) --"   
+          echo "--  $cmd --"   
+          echo "========================================="
+
+          cd tools/anim_to_vtk/${{ matrix.os }}
+          eval $cmd
+
+          cmd="./build.bash"
+          echo "========================================="
+          echo "--  BUILD tools for anim_to_vtk (${{ matrix.os }}) --"   
+          echo "--  $cmd --"   
+          echo "========================================="
+
+          cd ../../th_to_csv/${{ matrix.os }}
+          eval $cmd
+
+      # Upload artifact
+      - name: Upload built artifacts
+        uses: actions/upload-artifact@v3
+        with:
+          name: tools-${{ matrix.os }}
+          path: ${{ steps.set_workdir.outputs.value }}/exec
 
   build:
     if: ${{ github.repository_owner == 'OpenRadioss' }}
@@ -35,7 +113,7 @@ jobs:
       SERVBOT_PAT: ${{ secrets.SERVBOT_PAT }}
 
     strategy:
-      # If one job fails othere are canceled
+      # If one job fails others are canceled
       fail-fast: true
       matrix:
         include:
@@ -388,6 +466,7 @@ jobs:
 
   delivery:
     needs: qa
+    needs: build_tools
     # needs: build
     # DEV ONLY # runs-on: dev_delivery
     runs-on: dev_delivery
