Test windows build

diff --git a/.github/workflows/prmerge_ci_main_testwindows.yml b/.github/workflows/prmerge_ci_main_testwindows.yml
--- a/.github/workflows/prmerge_ci_main_testwindows.yml
+++ b/.github/workflows/prmerge_ci_main_testwindows.yml
@@ -4,7 +4,7 @@ on:
 
   push:
     branches:
-      - mainXX
+      - main
 
 env:
   CLOSE_BRANCH: 0
@@ -37,32 +37,32 @@ jobs:
             os: win64
             binary: starter
 
-          - build: starter_win64_sp
-            precision: sp
-            os: win64
-            binary: starter
+          # - build: starter_win64_sp
+          #   precision: sp
+          #   os: win64
+          #   binary: starter
 
-          - build: engine_win64_impi
-            precision: dp
-            os: win64
-            binary: engine
-            mpi: impi
+          # - build: engine_win64_impi
+          #   precision: dp
+          #   os: win64
+          #   binary: engine
+          #   mpi: impi
 
-          - build: engine_win64_impi_sp
-            precision: sp
-            os: win64
-            binary: engine
-            mpi: impi
+          # - build: engine_win64_impi_sp
+          #   precision: sp
+          #   os: win64
+          #   binary: engine
+          #   mpi: impi
 
-          - build: engine_win64
-            precision: dp
-            os: win64
-            binary: engine
+          # - build: engine_win64
+          #   precision: dp
+          #   os: win64
+          #   binary: engine
 
-          - build: engine_win64_sp
-            precision: sp
-            os: win64
-            binary: engine
+          # - build: engine_win64_sp
+          #   precision: sp
+          #   os: win64
+          #   binary: engine
 
     steps:
 
@@ -85,6 +85,13 @@ jobs:
             rm OpenRadioss/exec -r -force
           }
 
+      - name: Running builds
+        shell: wsl-bash {0}
+        run : |
+          uname -a
+          ls -l
+          mpiexec.exe -version
+
       # Working with Olivier's fork for the testing
       # Get last git modifications, don't clean before (way to keep persistent obj files)
       # - uses: actions/checkout@v2
@@ -93,90 +100,90 @@ jobs:
       #     clean: 'false'
       #     lfs: 'true'
 
-      - name: Running builds
-        working-directory: ${{ steps.set_workdir.outputs.value }}
-        # Running cygwin from powershell or cmd => neither identation nor comment !
-        # Not using wsl because of cmake issue with linux/win pathes conversion
-        shell: cmd
-        run: >
-          call "C:\Program Files (x86)\Intel\oneAPI\setvars.bat" intel64 vs2019 && C:\cygwin64\bin\bash --login -c "
-          cd %cd:\=/%;
-          cd OpenRadioss;
-          pwd;
-          git pull;
-          mpi_opts='';
-          if [ ! -z ${{ matrix.mpi }} ]; then mpi_opts='-mpi=${{ matrix.mpi }}'; fi;
-          cmd=\"./build_script.sh -arch=${{ matrix.os }} -prec=${{ matrix.precision }} -nt=${{ env.BUILD_NB_THREAD }} $mpi_opts\";
-          echo \"=========================================\";
-          echo \"--  BUILD ${{ matrix.build }} --\";
-          echo \"--  $cmd --\";
-          echo \"=========================================\";        
-          mkdir exec;
-          cd ${{ matrix.binary }};
-          eval $cmd;
-          cd ..;
-          md5sum exec/* || exit 1;
-          echo \"STATUS_BUILD=1\" >> $GITHUB_ENV;
-          "
+      # - name: Running builds
+      #   working-directory: ${{ steps.set_workdir.outputs.value }}
+      #   # Running cygwin from powershell or cmd => neither identation nor comment !
+      #   # Not using wsl because of cmake issue with linux/win pathes conversion
+      #   shell: cmd
+      #   run: >
+      #     call "C:\Program Files (x86)\Intel\oneAPI\setvars.bat" intel64 vs2019 && C:\cygwin64\bin\bash --login -c "
+      #     cd %cd:\=/%;
+      #     cd OpenRadioss;
+      #     pwd;
+      #     git pull;
+      #     mpi_opts='';
+      #     if [ ! -z ${{ matrix.mpi }} ]; then mpi_opts='-mpi=${{ matrix.mpi }}'; fi;
+      #     cmd=\"./build_script.sh -arch=${{ matrix.os }} -prec=${{ matrix.precision }} -nt=${{ env.BUILD_NB_THREAD }} $mpi_opts\";
+      #     echo \"=========================================\";
+      #     echo \"--  BUILD ${{ matrix.build }} --\";
+      #     echo \"--  $cmd --\";
+      #     echo \"=========================================\";        
+      #     mkdir exec;
+      #     cd ${{ matrix.binary }};
+      #     eval $cmd;
+      #     cd ..;
+      #     md5sum exec/* || exit 1;
+      #     echo \"STATUS_BUILD=1\" >> $GITHUB_ENV;
+      #     "
 
-      - name: Managing step execution
-        if: ${{ always() }}
-        # Running cygwin from powershell or cmd => neither identation nor comment !
-        shell: cmd
-        run: >
-          call C:\cygwin64\bin\bash --login -c "
-          MAILMSG=\"Some error(s) has(ve) been raised during workflow execution:\n\n\";
-          echo -e \"\n#### STATUS_STEP_BUILD ${{ matrix.build }} ###\";
-          if [ ${{ env.STATUS_BUILD }} = 0 ];
-          then
-          echo -e \"Status\t[ \033[31;2;1mFAILED\033[0m ]\";
-          MAILMSG+=\"The build ${{ matrix.build }} has failed \n\";
-          echo \"CLOSE_BRANCH=1\" >> $GITHUB_ENV;
-          echo -e $MAILMSG;
-          echo -e \"$MAILMSG\nThe branch is closed\" | Email -f $FROM_EMAIL -s \"Error in Github CI repo ${{ github.repository }} (${{github.sha}})\" -r $MAIL_RELAY $TO_EMAIL;
-          exit 1;
-          else
-          echo -e \"Status\t[ \033[32;2;1mOK\033[0m ]\";
-          fi;   
-          "
-      # Upload artifact
-      - name: Upload built artifacts
-        uses: actions/upload-artifact@v3
-        with:
-          name: bins-${{ matrix.os }}-${{ matrix.precision }}
-          # Working with Olivier's fork for the testing
-          # path: ${{ steps.set_workdir.outputs.value }}/exec
-          path: ${{ steps.set_workdir.outputs.value }}/OpenRadioss/exec
-        if: ${{ env.CLOSE_BRANCH == 0 }}           
+      # - name: Managing step execution
+      #   if: ${{ always() }}
+      #   # Running cygwin from powershell or cmd => neither identation nor comment !
+      #   shell: cmd
+      #   run: >
+      #     call C:\cygwin64\bin\bash --login -c "
+      #     MAILMSG=\"Some error(s) has(ve) been raised during workflow execution:\n\n\";
+      #     echo -e \"\n#### STATUS_STEP_BUILD ${{ matrix.build }} ###\";
+      #     if [ ${{ env.STATUS_BUILD }} = 0 ];
+      #     then
+      #     echo -e \"Status\t[ \033[31;2;1mFAILED\033[0m ]\";
+      #     MAILMSG+=\"The build ${{ matrix.build }} has failed \n\";
+      #     echo \"CLOSE_BRANCH=1\" >> $GITHUB_ENV;
+      #     echo -e $MAILMSG;
+      #     echo -e \"$MAILMSG\nThe branch is closed\" | Email -f $FROM_EMAIL -s \"Error in Github CI repo ${{ github.repository }} (${{github.sha}})\" -r $MAIL_RELAY $TO_EMAIL;
+      #     exit 1;
+      #     else
+      #     echo -e \"Status\t[ \033[32;2;1mOK\033[0m ]\";
+      #     fi;   
+      #     "
+      # # Upload artifact
+      # - name: Upload built artifacts
+      #   uses: actions/upload-artifact@v3
+      #   with:
+      #     name: bins-${{ matrix.os }}-${{ matrix.precision }}
+      #     # Working with Olivier's fork for the testing
+      #     # path: ${{ steps.set_workdir.outputs.value }}/exec
+      #     path: ${{ steps.set_workdir.outputs.value }}/OpenRadioss/exec
+      #   if: ${{ env.CLOSE_BRANCH == 0 }}           
 
-      # Close the branch (= restrict push to team devopsadmins) if needed
-      # Owner is not mandatory here ... PAT is sufficient ??? seems that as servbot has permissions on this repo so his PAT is sufficient ...
-      - uses: octokit/request-action@v2.x
-        id: close_branch_build
-        env:
-          GITHUB_TOKEN: ${{ env.SERVBOT_PAT }}
-          REQUEST_BODY: "['${{ env.TEAM_RESTRICTIVE_CLOSED_BRANCH}}']"
-        with:
-          route: PUT /repos/${{ github.repository }}/branches/main/protection/restrictions/teams
-          data: ${{ env.REQUEST_BODY }}
-        if: ${{ always() && env.CLOSE_BRANCH == 1 }}         
+      # # Close the branch (= restrict push to team devopsadmins) if needed
+      # # Owner is not mandatory here ... PAT is sufficient ??? seems that as servbot has permissions on this repo so his PAT is sufficient ...
+      # - uses: octokit/request-action@v2.x
+      #   id: close_branch_build
+      #   env:
+      #     GITHUB_TOKEN: ${{ env.SERVBOT_PAT }}
+      #     REQUEST_BODY: "['${{ env.TEAM_RESTRICTIVE_CLOSED_BRANCH}}']"
+      #   with:
+      #     route: PUT /repos/${{ github.repository }}/branches/main/protection/restrictions/teams
+      #     data: ${{ env.REQUEST_BODY }}
+      #   if: ${{ always() && env.CLOSE_BRANCH == 1 }}         
 
-      # If the closing went wrong we send an email
-      - name: "Check result of closing branch and warn if it fails"
-        # Running cygwin from powershell or cmd => neither identation nor comment !
-        shell: cmd
-        run: >
-          call C:\cygwin64\bin\bash --login -c "
-          MAILMSG=\"Some error(s) has(ve) been raised during workflow execution:\n\n\";
-          MAILMSG+=\"A branch closing is needed but has failed\n\n\";
-          MAILMSG+=\"Return status API is : ${{ steps.close_branch_build.outputs.status }}\n\n\";
-          MAILMSG+=\"Check more detailed datas in CI logs\n\";
-          echo -e $MAILMSG;
-          echo -e \"\nClose return data API is : ${{ steps.close_branch_build.outputs.data }}\";
-          echo -e \"$MAILMSG\" | Email -f $FROM_EMAIL -s \"Error in Github CI repo ${{ github.repository }} (${{github.sha}}) on closing branch\" -r $MAIL_RELAY $TO_EMAIL;
-          exit 1;
-          "
-        if: ${{ always() && env.CLOSE_BRANCH == 1 && steps.close_branch_build.outputs.status != 200 }} 
+      # # If the closing went wrong we send an email
+      # - name: "Check result of closing branch and warn if it fails"
+      #   # Running cygwin from powershell or cmd => neither identation nor comment !
+      #   shell: cmd
+      #   run: >
+      #     call C:\cygwin64\bin\bash --login -c "
+      #     MAILMSG=\"Some error(s) has(ve) been raised during workflow execution:\n\n\";
+      #     MAILMSG+=\"A branch closing is needed but has failed\n\n\";
+      #     MAILMSG+=\"Return status API is : ${{ steps.close_branch_build.outputs.status }}\n\n\";
+      #     MAILMSG+=\"Check more detailed datas in CI logs\n\";
+      #     echo -e $MAILMSG;
+      #     echo -e \"\nClose return data API is : ${{ steps.close_branch_build.outputs.data }}\";
+      #     echo -e \"$MAILMSG\" | Email -f $FROM_EMAIL -s \"Error in Github CI repo ${{ github.repository }} (${{github.sha}}) on closing branch\" -r $MAIL_RELAY $TO_EMAIL;
+      #     exit 1;
+      #     "
+      #   if: ${{ always() && env.CLOSE_BRANCH == 1 && steps.close_branch_build.outputs.status != 200 }} 
 
   # qa_windows_no_container:
 
