Test windows build

diff --git a/.github/workflows/prmerge_ci_main_testwindows.yml b/.github/workflows/prmerge_ci_main_testwindows.yml
--- a/.github/workflows/prmerge_ci_main_testwindows.yml
+++ b/.github/workflows/prmerge_ci_main_testwindows.yml
@@ -122,8 +122,29 @@ jobs:
 
       - name: Managing step execution
         if: ${{ always() }}
-        run: |
-          C:\cygwin64\bin\bash --login -c "
-          echo 'Salut1'; \
-          echo 'Salut2'; \
+        run: >
+          C:\cygwin64\bin\bash --login -i -c "
+          MAILMSG='Some error(s) has(ve) been raised during workflow execution:\n\n'; \
+          echo -e '\n#### STATUS_STEP_BUILD ${{ matrix.build }} ###'; \
+          if [ '${{ env.STATUS_BUILD }}' = 0 ]
+          then
+            echo -e 'Status\t[ \033[31;2;1mFAILED\033[0m ]' ; \
+            MAILMSG='The build ${{ matrix.build }} has failed \n'; \
+
+            # Send email 
+            # Close the branch 
+            echo 'CLOSE_BRANCH=1' >> $GITHUB_ENV; \
+
+            # Print message in log 
+            echo -e $MAILMSG; \
+
+            # Send email
+            echo -e '$MAILMSG\nThe branch is closed' | Eail -f $FROM_EMAIL -s 'Error in Github CI repo ${{ github.repository }} (${{github.sha}})' -r $MAIL_RELAY $TO_EMAIL; \
+
+            # Exit fail to see it as a failure
+            exit 1; \
+
+          else
+            echo -e 'Status\t[ \033[32;2;1mOK\033[0m ]'; \
+          fi;
           "     
