Test windows build

diff --git a/.github/workflows/prmerge_ci_main_testwindows.yml b/.github/workflows/prmerge_ci_main_testwindows.yml
--- a/.github/workflows/prmerge_ci_main_testwindows.yml
+++ b/.github/workflows/prmerge_ci_main_testwindows.yml
@@ -97,7 +97,7 @@ jobs:
         shell: cmd
         run: >
           call "C:\Program Files (x86)\Intel\oneAPI\setvars.bat" intel64 vs2019 && C:\cygwin64\bin\bash --login -i -c "
-          echo "STATUS_BUILD=145" >> $GITHUB_ENV;
+          echo "STATUS_BUILD=0" >> $GITHUB_ENV;
           "
 
         # call "C:\Program Files (x86)\Intel\oneAPI\setvars.bat" intel64 vs2019 && C:\cygwin64\bin\bash --login -i -c "
@@ -139,6 +139,12 @@ jobs:
 
               # Print message in log 
               echo -e $MAILMSG; \
+
+              # Send email
+              echo -e "$MAILMSG\nThe branch is closed" | Eail -f $FROM_EMAIL -s "Error in Github CI repo ${{ github.repository }} (${{github.sha}})" -r $MAIL_RELAY $TO_EMAIL
+
+              # Exit fail to see it as a failure
+              exit 1
 
             else
               echo -e 'Status\t[ \033[32;2;1mOK\033[0m ]'; \
